### ISSUE TITLE
position relation encoders块

### ISSUE THREAD

**Issue by mitu752** [xiuqhou/Relation-DETR#12]
### Question

请问下论文提到的的移植性position relation encoders块是代码的哪个部分

**Comment by mitu752** [comment]
感谢 期待集成position relation encoder模型的发布

**Comment by xiuqhou** [comment]
感谢关注哈，我先更新了集成position relation的增强版DINO，配置文件为 [configs/dino++/dino++_resnet50_800_1333.py](https://github.com/xiuqhou/Relation-DETR/blob/main/configs/dino%2B%2B/dino%2B%2B_resnet50_800_1333.py)，模型文件在 [models/detectors/dino.py](https://github.com/xiuqhou/Relation-DETR/blob/main/models/detectors/dino.py) 和 [models/bricks/dino_transformer.py](https://github.com/xiuqhou/Relation-DETR/blob/main/models/bricks/dino_transformer.py)，权重也上传了🤗可以先看看哦，其他模型还在整理中...
