### ISSUE TITLE
Objects365 checkpoint

### ISSUE THREAD

**Issue by xternalz** [xiuqhou/Relation-DETR#14]
### Description

Hi, thanks for the nice work. Would you release the objects365 checkpoint (before it's finetuned on COCO)?

### Use case

It would be helpful to people who want to finetune it on custom datasets.

**Comment by xiuqhou** [comment]
Hi, thanks for your advice. Our server system is being updated now. After that, if the pretrained weight on object365 has not been deleted, I will release it.

**Comment by xiuqhou** [comment]
Hi, object365 checkpoint is now available [here](https://github.com/xiuqhou/Relation-DETR/releases/download/v1.0.0/relation_detr_focalnet_large_lrf_fl4_800_1333_o365_4e.pth) ! Thanks again for your advice.
