### ISSUE TITLE
[Bug]: ReadMe中Relation-DETR with Focal-L(IN-22K)的config地址配置错误

### ISSUE THREAD

**Issue by DoctorDream** [xiuqhou/Relation-DETR#18]
### Bug

ReadMe中Relation-DETR with Focal-L(IN-22K)的config地址配置错误，直接点击无法正常跳转至对应的config，需要将\修改成/

**Comment by DoctorDream** [comment]
> 哈喽，当时是在windows上复制粘贴的路径，没注意分隔符的问题🤣这会儿已经改过来啦~多谢指出问题

您好，我使用两张24G的3090显卡，batch_size设为1，img_size设置为600-600，但是好像还是会爆显存无法训练，请问这是否是因为我有别的地方配置错了，还是24G确实不够训练？
我的环境为：
```
sys.platform                     linux
Python                           3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0]
numpy                            1.24.4
PyTorch                          2.0.1 @/opt/conda/lib/python3.10/site-packages/torch
PyTorch debug build              False
torch._C._GLIBCXX_USE_CXX11_ABI  False
GPU available                    Yes
GPU 0,1                          NVIDIA GeForce RTX 3090 (arch=8.6)
Driver version                   515.105.01
CUDA_HOME                        None - invalid!
Pillow                           9.4.0
torchvision                      0.15.2 @/opt/conda/lib/python3.10/site-packages/torchvision
torchvision arch flags           /opt/conda/lib/python3.10/site-packages/torchvision/_C.so
fvcore                           0.1.5.post20221221
iopath                           0.1.10
cv2                              4.10.0
```

**Comment by xiuqhou** [comment]
Hi @DoctorDream 

3090的24G显存足够训练了，如果用的Focalnet-large 800*1333的配置，可以把默认配置的5层特征图改成4层，冻结1层backbone，issue https://github.com/xiuqhou/Relation-DETR/issues/15 中有更改后的配置。

如果您修改了img_size，需要把[train_transform](https://github.com/xiuqhou/Relation-DETR/blob/main/transforms/presets.py)中的使用的数据增强尺寸也相应修改，否则训练和推理的图片尺寸对不上，会降低性能。

**Comment by DoctorDream** [comment]
> Hi @DoctorDream
> 
> 3090的24G显存足够训练了，如果用的Focalnet-large 800*1333的配置，可以把默认配置的5层特征图改成4层，冻结1层backbone，issue #15 中有更改后的配置。
> 
> 如果您修改了img_size，需要把[train_transform](https://github.com/xiuqhou/Relation-DETR/blob/main/transforms/presets.py)中的使用的数据增强尺寸也相应修改，否则训练和推理的图片尺寸对不上，会降低性能。

嗯嗯好的，非常感谢
