### ISSUE TITLE
关于look forward twice

### ISSUE THREAD

**Issue by Baboom-l** [xiuqhou/Relation-DETR#19]
你好，我看到代码里没有使用look forward twice方式，请问是对结果会有负面影响吗。

**Comment by xiuqhou** [comment]
Hi @Baboom-l 

代码中是有look forward twice的，具体在
https://github.com/xiuqhou/Relation-DETR/blob/main/models/bricks/relation_transformer.py#L374-L377

这几行中我们中断了迭代更新前reference_points的梯度，而保留了更新后reference_points的梯度，其实就是look_forward_twice。

如果不用look_forward_twice，则应该中断更新后reference_points的梯度

**Comment by Baboom-l** [comment]
非常感谢您的回复，太及时啦！但是我看到355和356行额外加了个self.norm这个操作是不是可以去掉的，这样可以少算一次self.box_head。另外我看到代码里用的正余弦编码也和其它detr实现有些差别，是有什么特殊原因吗

**Comment by xiuqhou** [comment]
这里的box_head部分是沿用了DINO的做法：output_coord使用self.norm而reference_points不用self.norm。

但您的想法是可行的，如果都去掉self.norm或者都保留self.norm，reference_points可以沿用output_coord的结果，省去了一次box_head计算。甚至inverse_sigmoid的过程也可以只算一次。

但是要注意，look_forward_twice要求中断上一次reference_points的梯度，而保留当前reference_points的梯度，因此训练时是不能重用结果的，只能在推理时可以重用。具体实现参考下面这样：

```python
            inverse_ref_point = inverse_sigmoid(reference_points)
            output_class = self.class_head[layer_idx](self.norm(query))
            coord_delta = self.bbox_head[layer_idx](self.norm(query))
            output_coord = (coord_delta + inverse_ref_point).sigmoid()

            # get output, reference_points are not detached for look_forward_twice
            outputs_classes.append(output_class)
            outputs_coords.append(output_coord)

            if layer_idx == self.num_layers - 1:
                break

            # iterative bounding box refinement
            if self.training:
                # iterative bounding box refinement with look_forward_twice
                reference_points = (coord_delta + inverse_ref_point.detach()).sigmoid()
            else:
                # reuse output_coord for faster inference
                reference_points = output_coord
```

代码中正余弦编码只是写法和别的方法不太一样，避免重复的计算，最后结果是一样的
