### ISSUE TITLE
请求SA-Det-100数据集国内镜像

### ISSUE THREAD

**Issue by Carl12138aka** [xiuqhou/Relation-DETR#6]
### 功能描述

[SA-Det-100](https://huggingface.co/datasets/xiuqhou/SA-Det-100k)的链接被墙的结结实实的，请问是否可以提供百度网盘等方式，万分感谢！

**Comment by xiuqhou** [comment]
之前没预料到huggingface被墙了，我最近会把数据集再上传一份到国内网盘。这个数据集比较大，上传要花费几天时间。

huggingface有个镜像站也可以下载数据集：[https://hf-mirror.com/datasets/xiuqhou/SA-Det-100k/tree/main](https://hf-mirror.com/datasets/xiuqhou/SA-Det-100k/tree/main)

**Comment by Carl12138aka** [comment]
感谢您的回复！持续关注，祝好！
