### ISSUE TITLE
About FIg.1

### ISSUE THREAD

**Issue by ZHUXUHAN** [xiuqhou/Relation-DETR#7]
### Question

hi, excellent work, dear sir, can you provide the code for drawing the Fig. 1 [may not the original data]. i also need to compare our method in this way.

thanks

**Comment by xiuqhou** [comment]
Added to the TODO list, we will share the code later. Please star the repository and stay tuned for updates!

**Comment by ZHUXUHAN** [comment]
That's very exciting, already starred it, and looking forward to future updates.

**Comment by xiuqhou** [comment]
Hi @ZHUXUHAN
We have updated code for visualizing MC distribution, please check [visualization/mc_distribution.py](https://github.com/xiuqhou/Relation-DETR/blob/main/visualization/mc_distribution.ipynb)
