### ISSUE TITLE
关于ablation study

### ISSUE THREAD

**Issue by billbliss3** [xiuqhou/Relation-DETR#8]
### Question

这是一个非常棒的工作，我深受震撼。

想请教一个小问题。文中提出的relation是关于前后两层的bbox的计算。
请问作者有没有试过，每层单独做当前层的bbox的relation，并接入到self Attention中。

**Comment by xiuqhou** [comment]
这个我倒没试过，最初想着前后两层更有利于信息层之间的传递，也更符合由粗到精的思想。

不过使用前后两层计算bbox的话只能引入5层relation，如果用单层box算relation可以引入6层relation，也许效果会更好呢，有兴趣您可以尝试一下🤗

**Comment by billbliss3** [comment]
您好，您的来件已收到，我会尽快给您回复的。

Thanks for you e-mail.~~
I've got it and I will reply it as soon as possible .
